# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

#Assignment 1: Array Creation and Manipulation



#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

**Import Numpy**

In [2]:

import numpy as np

**Create a Random Array of 5*5 using Random function of numpy ranging from 1 to 20**

In [3]:

arr=np.random.randint(1,21,size=(5,5))
print(arr)

[[ 6 15  1  7  8]
 [15  9  3  3  9]
 [18 11 13  1 16]
 [11  7  1  5  3]
 [10  1 20 18 10]]


**Making the third row all 1. Here : means all rows. 2 means third column as index start from 0**

In [4]:

arr[:,2]=1

**Again printing row**

In [5]:

print(arr)

[[ 6 15  1  7  8]
 [15  9  1  3  9]
 [18 11  1  1 16]
 [11  7  1  5  3]
 [10  1  1 18 10]]


#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

**Creating Numpy array of shape 4,4 with values from 1 to 16**

In [6]:

arr2=np.arange(1,17).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


**Replacing the Diagonal element with 0**

In [7]:
np.fill_diagonal(arr2, 0)
print(arr2)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

**Task 1:** Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [8]:
arr_2_1 = np.arange(1, 37).reshape(6, 6)
print("Original Array:")
print(arr_2_1)

# Extraction (3rd to 5th rows -> index 2:5, 2nd to 4th columns -> index 1:4)
sub_arr = arr_2_1[2:5, 1:4]
print("\nExtracted Sub-array:")
print(sub_arr)

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Extracted Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


**Task 2:** Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [9]:
arr_2_2 = np.random.randint(1, 100, size=(5, 5))
print("Original Array:")
print(arr_2_2)

# Border elements extraction
# Top row, bottom row, left column (excluding corners), right column (excluding corners)
border_elements = np.concatenate([
    arr_2_2[0, :],          # Top row
    arr_2_2[-1, :],         # Bottom row
    arr_2_2[1:-1, 0],       # Left border (excluding top/bottom corner)
    arr_2_2[1:-1, -1]       # Right border (excluding top/bottom corner)
])
print("\nBorder Elements:")
print(border_elements)

Original Array:
[[ 5  2 86 25 75]
 [ 1 50 20 84 21]
 [ 4 96 23 17 68]
 [58 12 55 48 95]
 [23 52 21 70 69]]

Border Elements:
[ 5  2 86 25 75 23 52 21 70 69  1  4 58 21 68 95]


### Assignment 3: Array Operations

**Task 1:** Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [10]:
a = np.random.randint(1, 10, size=(3, 4))
b = np.random.randint(1, 10, size=(3, 4))

print("Array A:")
print(a)
print("\nArray B:")
print(b)

print("\nElement-wise Addition:")
print(a + b)

print("\nElement-wise Subtraction:")
print(a - b)

print("\nElement-wise Multiplication:")
print(a * b)

print("\nElement-wise Division:")
print(a / b)

Array A:
[[4 1 4 2]
 [4 4 6 8]
 [4 5 2 1]]

Array B:
[[7 6 4 1]
 [2 3 4 3]
 [8 4 4 3]]

Element-wise Addition:
[[11  7  8  3]
 [ 6  7 10 11]
 [12  9  6  4]]

Element-wise Subtraction:
[[-3 -5  0  1]
 [ 2  1  2  5]
 [-4  1 -2 -2]]

Element-wise Multiplication:
[[28  6 16  2]
 [ 8 12 24 24]
 [32 20  8  3]]

Element-wise Division:
[[0.57142857 0.16666667 1.         2.        ]
 [2.         1.33333333 1.5        2.66666667]
 [0.5        1.25       0.5        0.33333333]]


**Task 2:** Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [11]:
arr_3_2 = np.arange(1, 17).reshape(4, 4)
print("Array:")
print(arr_3_2)

row_sum = np.sum(arr_3_2, axis=1)
col_sum = np.sum(arr_3_2, axis=0)

print("\nRow-wise Sum:", row_sum)
print("Column-wise Sum:", col_sum)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise Sum: [10 26 42 58]
Column-wise Sum: [28 32 36 40]


### Assignment 4: Statistical Operations

**Task 1:** Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [12]:
arr_4_1 = np.random.randint(1, 100, size=(5, 5))
print("Array:")
print(arr_4_1)

print("\nMean:", np.mean(arr_4_1))
print("Median:", np.median(arr_4_1))
print("Standard Deviation:", np.std(arr_4_1))
print("Variance:", np.var(arr_4_1))

Array:
[[84 21 93 51 90]
 [27  8 57 41 79]
 [54 34 24 85 18]
 [55 69 92 32 79]
 [90 11  9 80 98]]

Mean: 55.24
Median: 55.0
Standard Deviation: 30.028359928574186
Variance: 901.7024


**Task 2:** Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [13]:
arr_4_2 = np.arange(1, 10).reshape(3, 3).astype(float)
print("Original Array:")
print(arr_4_2)

mean = np.mean(arr_4_2)
std = np.std(arr_4_2)

normalized_arr = (arr_4_2 - mean) / std
print("\nNormalized Array:")
print(normalized_arr)

Original Array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Normalized Array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

**Task 1:** Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [14]:
arr_2d_1 = np.random.randint(1, 10, size=(3, 3))
arr_1d_1 = np.array([10, 20, 30])

print("2D Array:")
print(arr_2d_1)
print("\n1D Array:")
print(arr_1d_1)

result_5_1 = arr_2d_1 + arr_1d_1
print("\nResult after broadcasting (addition):")
print(result_5_1)

2D Array:
[[7 6 7]
 [4 9 5]
 [8 5 2]]

1D Array:
[10 20 30]

Result after broadcasting (addition):
[[17 26 37]
 [14 29 35]
 [18 25 32]]


**Task 2:** Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [15]:
arr_2d_2 = np.random.randint(1, 10, size=(4, 4))
arr_1d_2 = np.array([1, 2, 3, 4])

print("2D Array:")
print(arr_2d_2)
print("\n1D Array:")
print(arr_1d_2)

# Reshape 1D array to (4, 1) to enable column-wise broadcasting
result_5_2 = arr_2d_2 - arr_1d_2.reshape(4, 1)
print("\nResult after broadcasting (subtraction column-wise):")
print(result_5_2)

2D Array:
[[2 6 9 3]
 [7 5 2 1]
 [8 6 4 1]
 [7 8 4 5]]

1D Array:
[1 2 3 4]

Result after broadcasting (subtraction column-wise):
[[ 1  5  8  2]
 [ 5  3  0 -1]
 [ 5  3  1 -2]
 [ 3  4  0  1]]


### Assignment 6: Linear Algebra

**Task 1:** Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [16]:
matrix_a = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 1]], dtype=float)
print("Matrix:")
print(matrix_a)

det = np.linalg.det(matrix_a)
inv = np.linalg.inv(matrix_a)
eigenvalues, _ = np.linalg.eig(matrix_a)

print(f"\nDeterminant: {det}")
print("\nInverse Matrix:")
print(inv)
print("\nEigenvalues:")
print(eigenvalues)

Matrix:
[[2. 1. 1.]
 [1. 3. 2.]
 [1. 0. 1.]]

Determinant: 4.000000000000001

Inverse Matrix:
[[ 0.75 -0.25 -0.25]
 [ 0.25  0.25 -0.75]
 [-0.75  0.25  1.25]]

Eigenvalues:
[4.         0.99999999 1.00000001]


**Task 2:** Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [17]:
mat_1 = np.random.randint(1, 10, size=(2, 3))
mat_2 = np.random.randint(1, 10, size=(3, 2))

print("Matrix 1 (2x3):")
print(mat_1)
print("\nMatrix 2 (3x2):")
print(mat_2)

result_mult = np.dot(mat_1, mat_2)
print("\nMatrix Multiplication Result (2x2):")
print(result_mult)

Matrix 1 (2x3):
[[1 9 3]
 [2 6 6]]

Matrix 2 (3x2):
[[1 9]
 [4 8]
 [6 5]]

Matrix Multiplication Result (2x2):
[[55 96]
 [62 96]]


### Assignment 7: Advanced Array Manipulation

**Task 1:** Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [18]:
arr_7_1 = np.arange(1, 10).reshape(3, 3)
print("Original (3x3):")
print(arr_7_1)

reshaped_1_9 = arr_7_1.reshape(1, 9)
print("\nReshaped to (1, 9):")
print(reshaped_1_9)

reshaped_9_1 = arr_7_1.reshape(9, 1)
print("\nReshaped to (9, 1):")
print(reshaped_9_1)

Original (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped to (1, 9):
[[1 2 3 4 5 6 7 8 9]]

Reshaped to (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**Task 2:** Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [19]:
arr_7_2 = np.random.randint(1, 50, size=(5, 5))
print("Original Array (5x5):")
print(arr_7_2)

flattened = arr_7_2.flatten()
print("\nFlattened Array:")
print(flattened)

restored = flattened.reshape(5, 5)
print("\nReshaped Back to (5, 5):")
print(restored)

Original Array (5x5):
[[49 26 40 49 43]
 [32 15  6 16 10]
 [10 29 26 26 27]
 [43 45 24 44 26]
 [28 13  5 11 17]]

Flattened Array:
[49 26 40 49 43 32 15  6 16 10 10 29 26 26 27 43 45 24 44 26 28 13  5 11
 17]

Reshaped Back to (5, 5):
[[49 26 40 49 43]
 [32 15  6 16 10]
 [10 29 26 26 27]
 [43 45 24 44 26]
 [28 13  5 11 17]]


### Assignment 8: Fancy Indexing and Boolean Indexing

**Task 1:** Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [20]:
arr_8_1 = np.random.randint(10, 99, size=(5, 5))
print("Array:")
print(arr_8_1)

# Corner indices: (0,0), (0,4), (4,0), (4,4)
row_indices = [0, 0, 4, 4]
col_indices = [0, 4, 0, 4]
corners = arr_8_1[row_indices, col_indices]

print("\nCorner Elements:")
print(corners)

Array:
[[92 66 85 87 16]
 [13 40 29 75 97]
 [77 45 65 29 76]
 [36 93 39 12 36]
 [59 61 66 17 30]]

Corner Elements:
[92 16 59 30]


**Task 2:** Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [21]:
arr_8_2 = np.random.randint(1, 20, size=(4, 4))
print("Original Array:")
print(arr_8_2)

arr_8_2[arr_8_2 > 10] = 10
print("\nModified Array (capped at 10):")
print(arr_8_2)

Original Array:
[[17 13 12 19]
 [13  6 11 10]
 [ 3 12 16 12]
 [14  2  4  4]]

Modified Array (capped at 10):
[[10 10 10 10]
 [10  6 10 10]
 [ 3 10 10 10]
 [10  2  4  4]]


### Assignment 9: Structured Arrays

**Task 1:** Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [22]:
dtype_9_1 = [('name', 'U20'), ('age', 'i4'), ('weight', 'f4')]
data_9_1 = [
    ('Alice', 25, 55.5),
    ('Bob', 20, 72.0),
    ('Charlie', 30, 68.2)
]

structured_arr = np.array(data_9_1, dtype=dtype_9_1)
print("Original Structured Array:")
print(structured_arr)

sorted_arr = np.sort(structured_arr, order='age')
print("\nSorted by Age:")
print(sorted_arr)

Original Structured Array:
[('Alice', 25, 55.5) ('Bob', 20, 72. ) ('Charlie', 30, 68.2)]

Sorted by Age:
[('Bob', 20, 72. ) ('Alice', 25, 55.5) ('Charlie', 30, 68.2)]


**Task 2:** Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [23]:
dtype_9_2 = [('x', 'i4'), ('y', 'i4')]
points_data = [(1, 2), (4, 6), (7, 10)]
points = np.array(points_data, dtype=dtype_9_2)

print("Points:")
print(points)

# Compute pairwise Euclidean distances
n_points = len(points)
print("\nPairwise Euclidean Distances:")
for i in range(n_points):
    for j in range(i + 1, n_points):
        p1 = points[i]
        p2 = points[j]
        distance = np.sqrt((p1['x'] - p2['x'])**2 + (p1['y'] - p2['y'])**2)
        print(f"Distance between Point {i} {p1} and Point {j} {p2}: {distance:.2f}")

Points:
[(1,  2) (4,  6) (7, 10)]

Pairwise Euclidean Distances:
Distance between Point 0 (1, 2) and Point 1 (4, 6): 5.00
Distance between Point 0 (1, 2) and Point 2 (7, 10): 10.00
Distance between Point 1 (4, 6) and Point 2 (7, 10): 5.00


### Assignment 10: Masked Arrays

**Task 1:** Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [24]:
import numpy.ma as ma

raw_data_10 = np.random.randint(1, 20, size=(4, 4))
print("Raw Data:")
print(raw_data_10)

masked_arr_1 = ma.masked_greater(raw_data_10, 10)
print("\nMasked Array (elements > 10 masked):")
print(masked_arr_1)

print("\nSum of Unmasked Elements:", masked_arr_1.sum())

Raw Data:
[[18  5 15 16]
 [15 11  6 13]
 [14  4  5  9]
 [18  4 19 18]]

Masked Array (elements > 10 masked):
[[-- 5 -- --]
 [-- -- 6 --]
 [-- 4 5 9]
 [-- 4 -- --]]

Sum of Unmasked Elements: 33


**Task 2:** Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [25]:
raw_data_10_2 = np.random.randint(1, 20, size=(3, 3))
print("Raw Data:")
print(raw_data_10_2)

# Create a mask for the diagonal elements
diagonal_mask = np.eye(3, dtype=bool)
masked_arr_2 = ma.array(raw_data_10_2, mask=diagonal_mask)
print("\nMasked Array (diagonal masked):")
print(masked_arr_2)

mean_val = masked_arr_2.mean()
print(f"\nMean of unmasked elements: {mean_val:.2f}")

filled_arr = masked_arr_2.filled(mean_val)
print("\nArray with masked diagonal elements replaced by mean:")
print(filled_arr)

Raw Data:
[[11  1  9]
 [ 3  5 19]
 [ 7 17 12]]

Masked Array (diagonal masked):
[[-- 1 9]
 [3 -- 19]
 [7 17 --]]

Mean of unmasked elements: 9.33

Array with masked diagonal elements replaced by mean:
[[ 9  1  9]
 [ 3  9 19]
 [ 7 17  9]]
