# NumPy Tasks

In [31]:
import numpy as np
np.random.seed(42)

## Assignment 1: Array Creation and Manipulation

### Task 1

In [32]:
a = np.random.randint(1, 21, (5, 5))
a[:, 2] = 1
print(a)

[[ 7 20  1 11  8]
 [ 7 19  1 11  4]
 [ 8  3  1 12  6]
 [ 2  1  1 12 17]
 [10 16  1 15 19]]


### Task 2

In [33]:
a = np.arange(1, 17).reshape(4, 4)
np.fill_diagonal(a, 0)
print(a)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


## Assignment 2: Array Indexing and Slicing

### Task 1

In [34]:
a = np.arange(1, 37).reshape(6, 6)
print(a[2:5, 1:4])

[[14 15 16]
 [20 21 22]
 [26 27 28]]


### Task 2

In [35]:
a = np.random.randint(1, 50, (5, 5))
border = np.concatenate([a[0], a[-1], a[1:-1, 0], a[1:-1, -1]])
print(a)
print(border)

[[44  3 37  7 21]
 [ 9 39 18  4 25]
 [14  9 26  2 20]
 [28 47  7 44  8]
 [47 35 14 17 36]]
[44  3 37  7 21 47 35 14 17 36  9 14 28 25 20  8]


## Assignment 3: Array Operations

### Task 1

In [36]:
a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(1, 10, (3, 4))
print(a + b)
print("-" * 15)

print(a - b)
print("-" * 15)

print(a * b)
print("-" * 15)

print(a / b)

[[ 9 17 12  7]
 [ 8 11 12 15]
 [11  3 13 15]]
---------------
[[-5 -1 -4 -3]
 [ 4  1 -4 -3]
 [-7  1 -5  1]]
---------------
[[14 72 32 10]
 [12 30 32 54]
 [18  2 36 56]]
---------------
[[0.28571429 0.88888889 0.5        0.4       ]
 [3.         1.2        0.5        0.66666667]
 [0.22222222 2.         0.44444444 1.14285714]]


### Task 2

In [37]:
a = np.arange(1, 17).reshape(4, 4)
print(a.sum(axis=1))
print(a.sum(axis=0))

[10 26 42 58]
[28 32 36 40]


## Assignment 4: Statistical Operations

### Task 1

In [38]:
a = np.random.randint(1, 50, (5, 5))
print(a.mean(), np.median(a), a.std(), a.var())

23.12 24.0 14.24730149888041 202.98559999999998


### Task 2

In [39]:
a = np.arange(1, 10).reshape(3, 3)
z = (a - a.mean()) / a.std()
print(z)
print(z.mean(), z.std())

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0 1.0


## Assignment 5: Broadcasting

### Task 1

In [40]:
a = np.random.randint(1, 10, (3, 3))
row = np.array([10, 20, 30])
print(a + row)

[[18 25 33]
 [18 26 33]
 [11 23 35]]


### Task 2

In [41]:
a = np.random.randint(1, 10, (4, 4))
v = np.array([1, 2, 3, 4])
print(a - v[:, np.newaxis])

[[ 2  0  4  6]
 [ 5  7  1  5]
 [-2  1  1  2]
 [ 3  3  0  3]]


## Assignment 6: Linear Algebra

### Task 1

In [42]:
m = np.array([[2, 1, 3], [0, 4, 1], [5, 2, 1]])
print(np.linalg.det(m))
print(np.linalg.inv(m))
print(np.linalg.eigvals(m))

-51.0
[[-0.03921569 -0.09803922  0.21568627]
 [-0.09803922  0.25490196  0.03921569]
 [ 0.39215686 -0.01960784 -0.15686275]]
[-2.48267294+0.j  6.1334198 +0.j  3.34925315+0.j]


### Task 2

In [43]:
a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (3, 2))
print(a @ b)

[[ 68  65]
 [ 87 104]]


## Assignment 7: Advanced Array Manipulation

### Task 1

In [44]:
a = np.arange(1, 10).reshape(3, 3)
print(a.reshape(1, 9))
print(a.reshape(9, 1))

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### Task 2

In [45]:
a = np.random.randint(1, 50, (5, 5))
flat = a.flatten()
print(flat)
print(flat.reshape(5, 5))

[27 13 41  3 39  6  8 27  9 37 33 42 44 24 15 32 32 24 41 49 49 12 39  2
  3]
[[27 13 41  3 39]
 [ 6  8 27  9 37]
 [33 42 44 24 15]
 [32 32 24 41 49]
 [49 12 39  2  3]]


## Assignment 8: Fancy Indexing and Boolean Indexing

### Task 1

In [46]:
a = np.random.randint(1, 50, (5, 5))
print(a[[0, 0, -1, -1], [0, -1, 0, -1]])

[49 49  4 24]


### Task 2

In [47]:
a = np.random.randint(1, 20, (4, 4))
a[a > 10] = 10
print(a)

[[ 5  2  6 10]
 [10 10  1  9]
 [ 6 10  3  4]
 [10  3 10  7]]


## Assignment 9: Structured Arrays

### Task 1

In [48]:
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
people = np.array([('Ali', 25, 70.5), ('Sara', 22, 55.0), ('Omar', 30, 82.3)], dtype=dt)
print(np.sort(people, order='age'))

[('Sara', 22, 55. ) ('Ali', 25, 70.5) ('Omar', 30, 82.3)]


### Task 2

In [49]:
pts = np.array([(0, 0), (3, 4), (6, 8)], dtype=[('x', 'i4'), ('y', 'i4')])
dx = pts['x'][:, None] - pts['x'][None, :]
dy = pts['y'][:, None] - pts['y'][None, :]
print(np.sqrt(dx**2 + dy**2))

[[ 0.  5. 10.]
 [ 5.  0.  5.]
 [10.  5.  0.]]


## Assignment 10: Masked Arrays

### Task 1

In [50]:
a = np.random.randint(1, 20, (4, 4))
m = np.ma.masked_greater(a, 10)
print(m)
print(m.sum())

[[9 1 8 7]
 [-- 8 1 --]
 [-- 10 3 7]
 [-- -- -- 2]]
56


### Task 2

In [51]:
a = np.random.randint(1, 20, (3, 3)).astype(float)
m = np.ma.masked_array(a, mask=np.eye(3, dtype=bool))
print(m.filled(m.mean()))

[[ 9. 16. 12.]
 [ 5.  9.  9.]
 [ 9.  3.  9.]]
